### ISSUE TITLE
Escape special markdown characters for ADOWiki

### ISSUE THREAD

**Issue by webyhwh** [microsoft/Dual-write-automations#29]
Some data can be truncated in the Wiki, the good example is the filter like this - "((PartyType == "Organization") || (PartyType == "Person"))". "||" is considered as markdown table and you'll see only "((PartyType == "Organization")" part as a result. 

Current behavior: ((PartyType == "Organization") || (PartyType == "Person"))
Expected behavior: ((PartyType == "Organization") \\|\\| (PartyType == "Person"))

**Comment by shahvarun89** [comment]
Hello I keep getting an error when try to upload to azure wiki. It creates the summary page but does not add any data or create any child pages. Have you faced this ? 

System.NullReferenceException: Object reference not set to an instance of an object.
   at DWLibary.Engines.DWADOWikiEngine.getFOEntity() in C:\Users\maxhentschel\source\repos\Dual-write-automationsv2\DWLibary\Engines\DWADOWikiEngine.cs:line 338
   at DWLibary.Engines.DWADOWikiEngine.createIndividualPageUpload() in C:\Users\maxhentschel\source\repos\Dual-write-automationsv2\DWLibary\Engines\DWADOWikiEngine.cs:line 149
   at DWLibary.Engines.DWADOWikiEngine.runMapUpload() in C:\Users\maxhentschel\source\repos\Dual-write-automationsv2\DWLibary\Engines\DWADOWikiEngine.cs:line 113 (51eec9ea)

**Comment by Hax1337** [comment]
@webyhwh  will look into the issue and add escape characters to it

**Comment by Hax1337** [comment]
This can be closed, fixed with release:
https://github.com/microsoft/Dual-write-automations/releases/tag/v1.0.7
