### ISSUE TITLE
Timeout when executed from powershell

### ISSUE THREAD

**Issue by ytaranovs** [microsoft/Dual-write-automations#31]
The following error occurs on a random basis.
With no changes to the script when run again - script succeeds.
Is there an option to configure timeout longer than 60 seconds?

Mode = Reset Link

-----
Starting Microsoft Edge WebDriver 123.0.2420.97 (ba5f45140663110c119b48e5add25da7c9e02bcc) on port 51016
2024-04-23T10:41:54.6306738Z To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver
2024-04-23T10:41:54.6307715Z 
2024-04-23T10:41:54.6310206Z Only local connections are allowed.
2024-04-23T10:41:54.6312257Z Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.
2024-04-23T10:41:54.6356622Z 
2024-04-23T10:41:54.8711704Z Microsoft Edge WebDriver was started successfully.
fail: DWHelper.DWHostedService[0]
2024-04-23T10:42:57.5743875Z       OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:51016/session timed out after 60 seconds.
2024-04-23T10:42:57.5744822Z        ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing.
2024-04-23T10:42:57.5745195Z        ---> System.TimeoutException: The operation was canceled.
2024-04-23T10:42:57.5745529Z        ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
2024-04-23T10:42:57.5745953Z        ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
2024-04-23T10:42:57.5748134Z        ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
2024-04-23T10:42:57.5748533Z          --- End of inner exception stack trace ---
2024-04-23T10:42:57.5748906Z          at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2024-04-23T10:42:57.5749354Z          at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
2024-04-23T10:42:57.5749784Z          at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
2024-04-23T10:42:57.5750168Z          at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024-04-23T10:42:57.5750509Z          --- End of inner exception stack trace ---
2024-04-23T10:42:57.5750875Z          at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024-04-23T10:42:57.5751348Z          at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
2024-04-23T10:42:57.5751961Z          at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024-04-23T10:42:57.5752525Z          at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
2024-04-23T10:42:57.5753019Z          --- End of inner exception stack trace ---
2024-04-23T10:42:57.5753283Z          --- End of inner exception stack trace ---
2024-04-23T10:42:57.5753736Z          at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
2024-04-23T10:42:57.5754371Z          at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
2024-04-23T10:42:57.5754884Z          at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
2024-04-23T10:42:57.5755259Z          at OpenQA.Selenium.Remote.HttpCommandExecutor.<>c__DisplayClass33_0.<<Execute>b__0>d.MoveNext()
2024-04-23T10:42:57.5755573Z       --- End of stack trace from previous location ---
2024-04-23T10:42:57.5755900Z          at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
2024-04-23T10:42:57.5756212Z          --- End of inner exception stack trace ---
2024-04-23T10:42:57.5756509Z          at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
2024-04-23T10:42:57.5756866Z          at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
2024-04-23T10:42:57.5757245Z          at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2024-04-23T10:42:57.5757576Z          at OpenQA.Selenium.WebDriver.StartSession(ICapabilities capabilities)
2024-04-23T10:42:57.5757927Z          at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
2024-04-23T10:42:57.5758313Z          at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
2024-04-23T10:42:57.5758735Z          at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeDriverService service, EdgeOptions options, TimeSpan commandTimeout)
2024-04-23T10:42:57.5759864Z          at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeDriverService service, EdgeOptions options)
2024-04-23T10:42:57.5760332Z          at DWLibary.EdgeUniversal.getToken() in C:\Users\maxhentschel\source\repos\Dual-write-automationsv2\DWLibary\EdgeUniversal.cs:line 114
2024-04-23T10:42:57.5760843Z          at DWHelper.AppExecution.checkEdgeVersionAndRetrieveToken() in C:\Users\maxhentschel\source\repos\Dual-write-automationsv2\DualWriteHelper\AppExecution.cs:line 181
2024-04-23T10:42:57.5761440Z          at DWHelper.AppExecution.run() in C:\Users\maxhentschel\source\repos\Dual-write-automationsv2\DualWriteHelper\AppExecution.cs:line 89

**Comment by Hax1337** [comment]
What are the start parameters you used @ytaranovs
