### ISSUE TITLE
Issues with matching EdgeWebdriver

### ISSUE THREAD

**Issue by JoPe72** [microsoft/Dual-write-automations#41]
Hi All...

I am trying to get the DWHelperUI to work. When I run it, it seems like everything is OK. It is even downloading the correct driver (according to the log)... What am I missing?

Attaching the log:

2024-08-08 23:23:11: Commandline arguments parsed and set
2024-08-08 23:23:11: LogLevel Debug
2024-08-08 23:23:17:       Starting...
2024-08-08 23:23:17:       Background Service is working.  2024-08-08 23:23:17
2024-08-08 23:23:17:       Application started. Press Ctrl+C to shut down.
2024-08-08 23:23:17:       Hosting environment: Production
2024-08-08 23:23:17:       Content root path: C:\Users\JohanPersson\OneDrive - Business Engagement Group Sweden AB\Documents\3. Resources\Apps\DWHelper\DWHelper-standalone
2024-08-08 23:23:17:       Config path: C:\Users\JohanPersson\OneDrive - Business Engagement Group Sweden AB\Documents\3. Resources\Apps\DWHelper\DWHelper-standalone
2024-08-08 23:23:17:       Default configuration loaded
2024-08-08 23:23:18:       Get access token, opening Edge
2024-08-08 23:23:18:       Your Edge version: 128
2024-08-08 23:23:18:       Matching edge version with edge driver
2024-08-08 23:23:18: Starting Microsoft Edge WebDriver 128.0.2739.9 (97865d0761783f0a1ac9f56d9ad5ef7cfc792eab) on port 52940
2024-08-08 23:23:18: To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver
2024-08-08 23:23:18: Only local connections are allowed.
2024-08-08 23:23:18: Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.
2024-08-08 23:23:18: Microsoft Edge WebDriver was started successfully.
2024-08-08 23:23:18: msedgedriver was started successfully on port 52940.
2024-08-08 23:23:24: ERROR
2024-08-08 23:23:24:       OpenQA.Selenium.WebDriverException: Unexpected error creating WebSocket DevTools session.
2024-08-08 23:23:24:        ---> OpenQA.Selenium.WebDriverException: DevTools version is not in the supported range. Desired version=128, range=5. Supported versions: 123, 122, 121, 85
2024-08-08 23:23:24:          at OpenQA.Selenium.DevTools.DevToolsDomains.MatchDomainsVersion(Int32 desiredVersion, Int32 versionRange)
2024-08-08 23:23:24:          at OpenQA.Selenium.DevTools.DevToolsDomains.InitializeDomains(Int32 protocolVersion, DevToolsSession session, Int32 versionRange)
2024-08-08 23:23:24:          at OpenQA.Selenium.DevTools.DevToolsDomains.InitializeDomains(Int32 protocolVersion, DevToolsSession session)
2024-08-08 23:23:24:          at OpenQA.Selenium.DevTools.DevToolsSession.StartSession()
2024-08-08 23:23:25:          at OpenQA.Selenium.Chromium.ChromiumDriver.<>c__DisplayClass34_0.<<GetDevToolsSession>b__0>d.MoveNext()
2024-08-08 23:23:25:       --- End of stack trace from previous location ---
2024-08-08 23:23:25:          at OpenQA.Selenium.Chromium.ChromiumDriver.GetDevToolsSession(DevToolsOptions options)
2024-08-08 23:23:25:          --- End of inner exception stack trace ---
2024-08-08 23:23:25:          at OpenQA.Selenium.Chromium.ChromiumDriver.GetDevToolsSession(DevToolsOptions options)
2024-08-08 23:23:25:          at OpenQA.Selenium.Chromium.ChromiumDriver.GetDevToolsSession()
2024-08-08 23:23:25:          at DWLibary.EdgeUniversal.getToken() in C:\Users\maxhentschel\source\repos\Dual-write-automationsv2\DWLibary\EdgeUniversal.cs:line 117
2024-08-08 23:23:25:          at DWHelper.AppExecution.checkEdgeVersionAndRetrieveToken() in C:\Users\maxhentschel\source\repos\Dual-write-automationsv2\DualWriteHelper\AppExecution.cs:line 181
2024-08-08 23:23:25:          at DWHelper.AppExecution.run() in C:\Users\maxhentschel\source\repos\Dual-write-automationsv2\DualWriteHelper\AppExecution.cs:line 89
2024-08-08 23:23:25:       Application is shutting down...
2024-08-08 23:23:25:       Application stopped successful without errors!

**Comment by JoPe72** [comment]
Thanks to guidance from @Hax1337 I tried turning off Previews in Edge and it worked great.
